## example config file

############### CODEDIR ################
## snakemake code dir: snakemake must run from this dir
smk_home: "/home/amins/pipelines/snakemake/toymake"

############### WORKDIR ################
## path to store results
workdir: "/fastscratch/amins/snakemake/toymake"

############### CLUSTER ################
## paths are relative to snakemake code dir
cluster_specs: "confs/torque_helix.json"
prerun_script: "scripts/prerun.sh"
postrun_script: "scripts/postrun.sh"

## END ##
