## example config file

############### CODEDIR ################
## snakemake code dir: snakemake must run from this dir
## Prefer absolute path as symlinked dirs may return errors
smk_home: "/projects/verhaak-lab/amins/code/pipelines/snakemake/toymake"

############### WORKDIR ################
## path to store results
workdir: "/fastscratch/amins/snakemake/toymake"

############### CLUSTER ################
## paths are relative to snakemake code dir
## cluster_specs is now overriden by --profile config
## cluster_specs: "config/slurm_sumner_defaults.yaml"
prerun_script: "scripts/prerun.sh"
postrun_script: "scripts/postrun.sh"

## END ##
