__default__:
  partition: compute
  qos: batch
  mail-user: "{smk_username}@jax.org"
  mail-type: ALL
  export: all
  nodes: 1
  ntasks: 2
  time: '1:00:00'
  mem: 2G
step1:
  ntasks: 1
  time: '1:10:00'
step2:
  time: '1:40:00'
  mem: 1024
